# see docs in https://github.com/openai/codex/blob/main/docs/config.md

model = "gpt-5.2-codex"
model_reasoning_effort = "medium"
notify = ["ai-notify"]
network_access = true
sandbox_mode = "workspace-write"

[features]
web_search_request = true
unified_exec = true
apply_patch_freeform = true
skills = true
shell_snapshot = true

[tui]
notifications = false

[projects."/home/isymchych/accel-os"]
trust_level = "trusted"

[projects."/home/isymchych/work"]
trust_level = "trusted"

[projects."/home/isymchych/projects"]
trust_level = "trusted"

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex"]
enabled = false

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest", "--executable-path", "/usr/bin/chromium", "--extension"]
enabled = false
env = { "PLAYWRIGHT_MCP_EXTENSION_TOKEN" = "4ABNUUw41dr10RtRCTxvNUGoNsadvCq-PvdIfuKa77I" }

[notice]
hide_rate_limit_model_nudge = true
