name: Check bin-tools

on:
  push:
    branches: [main]
    paths:
      - bin-tools/**
  pull_request:
    branches: [main]
    paths:
      - bin-tools/**
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # toolchain must be selected before the rust-cache init
      - name: Use Rust
        run: rustup toolchain install stable --profile minimal

      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: bin-tools

      - name: Lint & test Rust
        working-directory: bin-tools
        run: cargo clippy --all-targets --all-features -- -D warnings && cargo test
